/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnswerPanel: typeof import('./src/components/AnswerPanel.vue')['default']
    Button: typeof import('primevue/button')['default']
    CircleProgressBar: typeof import('./src/components/CircleProgressBar.vue')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    HeaderBar: typeof import('./src/components/HeaderBar.vue')['default']
    HeaderBarButton: typeof import('./src/components/HeaderBarButton.vue')['default']
    HistoryFilter: typeof import('./src/components/HistoryFilter.vue')['default']
    HistoryList: typeof import('./src/components/HistoryList.vue')['default']
    HistoryListItem: typeof import('./src/components/HistoryListItem.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    QuestionCreatePanel: typeof import('./src/components/QuestionCreatePanel.vue')['default']
    QuestionList: typeof import('./src/components/QuestionList.vue')['default']
    QuestionListItem: typeof import('./src/components/QuestionListItem.vue')['default']
    QuestionSidebar: typeof import('./src/components/QuestionSidebar.vue')['default']
    Rating: typeof import('primevue/rating')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}
